Models/ClsBillete.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab2_MVC_Tamayo.Models
{
    public class ClsBillete
    {
        public int monto { get; set; }
        public int b100 { get; set; }
        public int b50 { get; set; }
        public int b20 { get; set; }
        public int b10 { get; set; }
    }
}

Models/ClsBisiesto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab2_MVC_Tamayo.Models
{
    public class ClsBisiesto
    {
        public int inicio { get; set; }
        public int termino { get; set; }
        public string bisiesto { get; set; }
        public string nobisiesto { get; set; }
        public string todo { get; set; }
        public string resultado { get; set; }
    }
}

Models/ClsPersona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab2_MVC_Tamayo.Models
{
    public class ClsPersona
    {
        public string apellido { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public bool sexo { get; set; }
        public int edad { get; set; }
        public double talla {get; set;}

    }
}

Controllers/BilleteController.cs
using Lab2_MVC_Tamayo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab2_MVC_Tamayo.Models;

namespace Lab2_MVC_Tamayo.Controllers
{
    public class BilleteController : Controller
    {
        // GET: Billete
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SuperIndex()
        {
            return View();
        }

        public ActionResult Visualizar(ClsBillete objBillete)
        {
            int cantidad;
            cantidad = objBillete.monto;

            int cant100, cant50, cant20m, cant10;
            int res100, res50, res20m, res10;

            cant100 = cantidad / 100;
            res100 = cantidad % 100;

            cant50 = res100 / 50;
            res50 = res100 % 50;

            cant20m = res50 / 20;
            res20m = res50 % 20;

            cant10 = res20m / 10;
            res10 = res20m % 10;

            objBillete.b100 = cant100;
            objBillete.b50 = cant50;
            objBillete.b20 = cant20m;
            objBillete.b10 = cant10;


            return View(objBillete);
        }
    }
}

Controllers/BisiestoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab2_MVC_Tamayo.Models;

namespace Lab2_MVC_Tamayo.Controllers
{
    public class BisiestoController : Controller
    {
        // GET: Bisiesto
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Visualizar(ClsBisiesto o)
        {

            return View(o);
        }
    }
}

Controllers/PersonaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab2_MVC_Tamayo.Models;
namespace Lab2_MVC_Tamayo.Controllers
{
    public class PersonaController : Controller
    {
        //si o si lo hizo
        //hcaer una cambio para personaasdasdasdasdasd
        List<ClsPersona> objLista = new List<ClsPersona>();
        // GET: Persona
        public ActionResult Index()
        {
            //Instanciar para el objeto 1
            ClsPersona objPersona1 = new ClsPersona();
            objPersona1.apellido = "Tamayo Conde";
            objPersona1.nombre = "Jaime";
            objPersona1.email = "jtamayo@upt.pe";
            objPersona1.sexo = true;
            objPersona1.edad = 27;
            objPersona1.talla = 1.69;
            objLista.Add(objPersona1);

            ClsPersona objPersona2 = new ClsPersona();
            objPersona2.apellido = "Tamayo Conde";
            objPersona2.nombre = "Oscar";
            objPersona2.email = "oscartc@gmail.com";
            objPersona2.sexo = true;
            objPersona2.edad = 30;
            objPersona2.talla = 1.73;
            objLista.Add(objPersona2);

            ClsPersona objPersona3 = new ClsPersona();
            objPersona3.apellido = "Damasco";
            objPersona3.nombre = "Yoselin";
            objPersona3.email = "yoselind@gmail.com";
            objPersona3.sexo = false;
            objPersona3.edad = 23;
            objPersona3.talla = 1.56;
            objLista.Add(objPersona3);

            return View(objLista);
        }
        
    }
}

Views/Billete/Index.cshtml
@model Lab2_MVC_Tamayo.Models.ClsBillete
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>


    <title>Cambio desde la vista</title>


</head>
<body>
    <div> 
        <h1>Cajero de Billetes</h1>
        <br /><br />
        <div>
            @using (Html.BeginForm("Visualizar", "Billete", FormMethod.Post))
            {
                <div>
                    @Html.LabelFor(model => model.monto, "Ingrese monto: ")
                    @Html.TextBoxFor(model => model.monto)
                </div>
                <br /><br />
                <input type="submit" value="Calcular" />
                <br /><br />
            }
        </div>
    </div>
</body>
</html>

Views/Billete/Visualizar.cshtml
@model Lab2_MVC_Tamayo.Models.ClsBillete
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Visualizar cambios</title>
</head>
<body>
    <div> 
        <h1>Cajero de billetes</h1>
        <div>
            <label>Monto: </label> @Model.monto <br /><br />
            <label>Billete de 100: </label> @Model.b100<br />
            <label>Billete de 50: </label>@Model.b50<br />
            <label>Billete de 20: </label>@Model.b20<br />
            <label>Billete de 10: </label>@Model.b10<br />
        </div>
    </div>
    <a href="Index"><< Retornar al formulario >></a>
</body>
</html>

Views/Bisiesto/Index.cshtml
@model Lab2_MVC_Tamayo.Models.ClsBisiesto
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <h1>Años Bisiestos y no  Bisiestos</h1> <br /><br />
        <div>
            @using (Html.BeginForm("Visualizar", "Bisiesto", FormMethod.Post))
            {
                <div>
                    @Html.LabelFor(model => model.inicio, "año inicio")

                    @Html.TextBoxFor(model => model.inicio)


                </div>
                <div>
                    @Html.LabelFor(model => model.termino, "año termino");

                    @Html.TextBoxFor(model => model.termino);


                </div>

                <label>
                    @Html.RadioButton("Anio", "Bisiestos", true)<label> Años Bisiestos</label> <br />
                </label>
                <label>
                    @Html.RadioButton("Anio", "NoBisiestos", true)<label> Años No Bisiestos</label> <br />
                </label>
                <label>
                    @Html.RadioButton("Anio", "Ambos", true)<label> Ambos</label> <br />
                </label>

                <br />
                <br />
                <input type="submit" value="Generar" />
            }
        </div>

    </div>
</body>
</html>

Views/Bisiesto/Visualizar.cshtml
@model Lab2_MVC_Tamayo.Models.ClsBisiesto
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Visualizar</title>
</head>
<body>
    <div>
        <h1> Años Bisiestos y No Bisiestos</h1>
        <br />
        <br />
        @{
            Model.bisiesto = "";
            Model.nobisiesto = "";
            Model.resultado = "";

            for (int i = Model.inicio; i <= Model.termino; i++)
            {
                Model.todo += ", ";
                if (i % 400 == 0)
                {
                    Model.bisiesto = Model.bisiesto + i + "\n";
                }
                else if (i % 400 == 0 & i % 100 != 0)
                {
                    Model.bisiesto = i + "\n";
                }
                else
                {
                    Model.nobisiesto += i + "\n";
                }
            }

            if (Request["Anio"].Equals("Bisiestos"))
            {
                Model.resultado = Model.bisiesto;
            }
            if (Request["Anio"].Equals("NoBisiestos"))
            {
                Model.resultado = Model.nobisiesto;
            }
            if (Request["Anio"].Equals("Ambos"))
            {
                Model.resultado = Model.todo;
            }
        }

        <h2><strong>@Request["Anio"]</strong></h2>
        <div>
            <strong> @Model.resultado</strong>
        </div>

        <a href="javascript:history.back()"> <<  retornar</a>
    </div>
</body>
</html>

Views/Persona/Index.cshtml
@model IEnumerable<Lab2_MVC_Tamayo.Models.ClsPersona>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        <center>
            <h1>Lista de Personas</h1>
            <br /><br />
            <table border="1" bordercolor="#0000FF">
                <tr>
                    <th>Apellido</th>
                    <th>Nombres</th>
                    <th>Email</th>
                    <th>Sexo</th>
                    <th>Edad</th>
                    <th>Talla</th>
                </tr>
                @foreach(var item in Model)
                { 
            <tr>
                <td>@Html.DisplayFor(modelItem => item.apellido)</td>
                <td>@Html.DisplayFor(modelItem => item.nombre)</td>
                <td>@Html.DisplayFor(modelItem => item.email)</td>
                <td>@Html.DisplayFor(modelItem => item.sexo)</td>
                <td>@Html.DisplayFor(modelItem => item.edad)</td>
                <td>@Html.DisplayFor(modelItem => item.talla)</td>
            </tr>
                }
            </table>
        </center>
    </div>
</body>
</html>